export const GETALLCATEGORIES = "GETALLCATEGORY"
export const CREATECATEGORY =  "CREATECATEGORY";

export const GETALLBRANDS = "GETALLBRANDS"
export const CREATEBRANDS =  "CREATEBRANDS";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";

export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"

export const CREATE_PRODUCT= "CREATE_PRODUCT"

export  const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT"

export const GET_CATEGORY = "GET_CATEGORY";

export const GET_BRAND = "GET_BRAND"
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"

export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_PRODUCT_PAGE = "GET_PRODUCT_PAGE"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const CREATE_NEW_USER = "CREATE_NEW_USER"

export const LOGIN_USER = "LOGIN_USER"

export const GET_CURRENT_USER = "GET_CURRENT_USER"

export const CREATE_REVIEW = "CREATE_REVIEW"

export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT"

export const DELTETE_REVIEW_PRODUCT = "DELTETE_REVIEW_PRODUCT"

export const UPDATE_REVIEW_PRODUCT = "UPDATE_REVIEW_PRODUCT";

export const ADD_WISHLIST = "ADD_WISHLIST"

export const DELETE_WISHLIST = "DELETE_WISHLIST"

export const GET_WISHLIST = "GET_WISHLIST"

export const CREATE_COUPON = "CREATE_COUPON"

export const GET_ALL_COUPON = "GET_ALL_COUPON"

export const DELETE_COUPON = "DELETE_COUPON"

export const GET_SPECFIC_COUPON = "GET_SPECFIC_COUPON"

export const UPDATE_COUPON = "UPDATE_COUPON"

export const CREATE_USER_ADDRESS = "CREATE_USER_ADDRESS"

export const GET_ALL_USER_ADDRESS = "GET_ALL_USER_ADDRESS"

export const DELETE_ADDRESS = "DELETE_ADDRESS"

export const UPDATE_ADDRESS = "UPDATE_ADDRESS"

export const GET_SPECFIC_ADDRESS = "GET_SPECFIC_ADDRESS"

export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER"

export const UPDATE__USER_PASSWORD = "UPDATE__USER_PASSWORD"

export const ADD_CART = "ADD_CART"

export const GET_ALL_CART = "GET_ALL_CART"

export const DELETE_ALL_CART = "DELETE_ALL_CART";

export const DELETE_SPECIFIC_CART = "DELETE_SPECIFIC_CART"

export const UPDATE_CART_QTY = "UPDATE_CART_QTY"

export const APPLY_COUPON = "APPLY_COUPON"

export const GET_ALL_PRODUCTS_CAT = "GET_ALL_PRODUCTS_CAT"

export const CREATE_CASH_ORDER = "CREATE_CASH_ORDER"

export const GET_ALL_ORDER = "GET_ALL_ORDER"

export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL"

export const CHANGE_ORDER = "CHANGE_ORDER"

export const CHANGE_ORDER_DELIVER = "CHANGE_ORDER_DELIVER"

export const CREATE_CARD_ORDER = "CREATE_CARD_ORDER"